"""
Export research results to JSON, CSV, and Markdown report formats.

Provides structured output for research sessions, enabling analysts
to save and share their findings.
"""

import json
import csv
import io
from datetime import datetime, timezone
from typing import Any

from src.utils import setup_logger
from src.exceptions import ExportError

logger = setup_logger(__name__)


def export_to_json(
    messages: list[dict[str, str]],
    metadata: dict[str, Any] | None = None,
) -> str:
    """Export research session to structured JSON.

    Args:
        messages: List of chat messages with 'role' and 'content' keys.
        metadata: Optional metadata (sources, chunk count, etc.).

    Returns:
        JSON string with research data.

    Raises:
        ExportError: If serialization fails.
    """
    try:
        # Build Q&A pairs from messages
        qa_pairs = []
        for i in range(0, len(messages) - 1, 2):
            if messages[i]["role"] == "user" and i + 1 < len(messages):
                qa_pairs.append({
                    "question": messages[i]["content"],
                    "answer": messages[i + 1]["content"],
                })

        export_data = {
            "tool": "Equity Research Tool",
            "exported_at": datetime.now(timezone.utc).isoformat(),
            "total_queries": len(qa_pairs),
            "conversations": qa_pairs,
            "metadata": metadata or {},
        }

        return json.dumps(export_data, indent=2, ensure_ascii=False)
    except Exception as e:
        raise ExportError("json", str(e))


def export_to_csv(
    messages: list[dict[str, str]],
) -> str:
    """Export research Q&A pairs to CSV format.

    Args:
        messages: List of chat messages with 'role' and 'content' keys.

    Returns:
        CSV string with columns: timestamp, question, answer.

    Raises:
        ExportError: If serialization fails.
    """
    try:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Timestamp", "Question", "Answer"])

        timestamp = datetime.now(timezone.utc).isoformat()
        for i in range(0, len(messages) - 1, 2):
            if messages[i]["role"] == "user" and i + 1 < len(messages):
                writer.writerow([
                    timestamp,
                    messages[i]["content"],
                    messages[i + 1]["content"],
                ])

        return output.getvalue()
    except Exception as e:
        raise ExportError("csv", str(e))


def generate_report(
    messages: list[dict[str, str]],
    sources: list[str] | None = None,
    metadata: dict[str, Any] | None = None,
) -> str:
    """Generate a Markdown research report from the session.

    Args:
        messages: List of chat messages.
        sources: List of source URLs used.
        metadata: Optional analytics metadata.

    Returns:
        Markdown-formatted research report.

    Raises:
        ExportError: If generation fails.
    """
    try:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        report = f"""# Equity Research Report

**Generated**: {timestamp}
**Tool**: Equity Research Tool — Hybrid RAG Pipeline

---

## Sources Analyzed

"""
        if sources:
            for i, src in enumerate(sources, 1):
                report += f"{i}. {src}\n"
        else:
            report += "*No sources recorded.*\n"

        report += "\n---\n\n## Research Q&A\n\n"

        qa_count = 0
        for i in range(0, len(messages) - 1, 2):
            if messages[i]["role"] == "user" and i + 1 < len(messages):
                qa_count += 1
                report += f"### Q{qa_count}: {messages[i]['content']}\n\n"
                report += f"{messages[i + 1]['content']}\n\n"
                report += "---\n\n"

        if qa_count == 0:
            report += "*No questions asked yet.*\n\n"

        if metadata:
            report += "## Session Analytics\n\n"
            report += "| Metric | Value |\n|---|---|\n"
            for key, value in metadata.items():
                report += f"| {key} | {value} |\n"
            report += "\n"

        report += "---\n\n*Generated by Equity Research Tool*\n"

        return report
    except Exception as e:
        raise ExportError("markdown", str(e))
